# Log
logging:
    level: 
        web: debug

spring:
    devtools:
        add-properties: true
 #datasourde
    datasource:
        driverClassName: org.h2.Driver
        url: jdbc:h2:mem:rpas-test
        username: sa
        password: 
    h2:
        console:
            enabled: true
            path: /h2-console
    jpa:
        properties: 
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: create
    batch:
        jdbc:
            initialize-schema: EMBEDDED
## MULTIPART (MultipartProperties)
# Enable multipart uploads
    servlet:
        multipart:
            location: ${user.dir}/webapps/websiteadmin/tmp