logging:
    level:
        root: WARN
        org:
            hibernate: error
            springframework:
                web: debug

#debug
debug: false

#Profile
spring:
#    application:
#        name: websiteadmin
    config:
        activate:
            on-profile: prod
    devtools:
        add-properties: false

## Datasourde
    datasource:
        driverClassName: org.postgresql.Driver
        url: ${PG_DATASOURCE_URL}
        username: ${PG_DATASOURCE_USERNAME}
        password: ${PG_DATASOURCE_PASSWORD}
        plataform: prod
        initialization-mode: ALWAYS
    jpa:
        show_sql: true
        properties: 
            dialect: org.hibernate.dialect.PostgreSQLDialect
## usado para controlar um BUG do postgresql
            jdbc:
                lob:
                    non_contextual_creation: true
            hibernate:
                format_sql: true
        hibernate:
            ddl-auto: update
# SQL prod/test
    sql:
        init:
            mode: NEVER
    batch:
        initialize-schema: NEVER
## MULTIPART (MultipartProperties)
# Enable multipart uploads
    servlet:
        multipart:
            location: ${user.dir}/webapps/websiteadmin/tmp

# Website admin properties
rpas:
    jwt:
        secret: YOt7Nk5a6di17yh5p8ctxgx5fDWp16g1RhZ9Ut4oYNEu9NA5Q7WaRXDIsgWf2qdFqfjEXlqcNleT7BDa0eJun1x2qXnM6sRgeg0CebUa7iaftHMxn7OaIgqaZgFFsoMaghZ4s6XMEWxf8mEdiyDpeYeSK7v5rC7HCRi0f5V2rojrWgTYof7KKPceUnVZZlhVNFftCUjvfZBORkme3mWwbV3SHJ7P7mxPOmpFRBrzdIB6rc5AZs7b8q3xyKxJhEywqJ9VTO7uJa6PFAV7XnQ3pCmcDBu9JyShL2IVZoXKESNDaFuRqKNd1AW36sz1sxgq6K65hggUSF2WrRgxsNTKHAY4FnX9dSEtcteMMtdNk9pmz0tvWgkI97F25AVYaRNdudkljG8dPBcCVOsFdFY3owJLzaWepwjYa0uKTmfAuIGbtIKqRt9OG9sDVjuf7osQLZpGPo8eTP8Y1i0jF0wZURRpJEr0gbmVvnIkYyNXc5HG656E6QWSrLY3lodoM3Q0
        expiration: 14400000
        audience: websiteadmin
        private.key: classpath:app.key
        public.key: classpath:app.pub
    from: no-reply@rpas.edu.br
    reset-password-token-expiration: 3600000
    reset-register-code-expiration: 3600000
    urlFrontEnd: http://10.10.2.14:3000

