#Env.H2_DATASOURCE_URL=jdbc:h2:mem:rpas-dev
#Env.H2_DATASOURCE_USERNAME=sa
#Env.H2_DATASOURCE_PASSWORD=
# porta do tomcat
server:
    port: 7000

#Profile
spring:
    profiles:
        active: prod
## MULTIPART (MultipartProperties)
# Enable multipart uploads
    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 200MB
            max-request-size: 215MB
# jpa
    jpa:
# This property will register an OpenEntityManagerInViewInterceptor, which 
# registers an EntityManager to the current thread, so you will have the same 
# EntityManager until the web request is finished
# see: https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot
        open-in-view: true
        defer-datasource-initialization: true

# Main
    main:
        allow-circular-references: true
        allow-bean-definition-overriding: true